# Generated by Django 5.1.2 on 2024-12-17 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("total_area", models.DecimalField(decimal_places=2, max_digits=10)),
                ("soil_type", models.CharField(max_length=50)),
                ("previous_crop", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("planting_date", models.DateField()),
                ("harvest_date", models.DateField()),
                ("daily_plan", models.JSONField()),
                ("pesticides", models.JSONField()),
                ("monitoring_frequency", models.CharField(max_length=50)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.farm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("task_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "crop_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cropplan"
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="PestAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pest_name", models.CharField(max_length=100)),
                ("risk_level", models.CharField(max_length=20)),
                ("detection_date", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
                ("recommended_action", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.farm"
                    ),
                ),
            ],
        ),
    ]
