# Generated by Django 5.1.2 on 2024-12-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cropplan",
            name="daily_plan",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cropplan",
            name="pesticides",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="farm",
            name="soil_type",
            field=models.CharField(
                choices=[
                    ("clay", "Clay"),
                    ("loam", "Loam"),
                    ("sandy", "Sandy"),
                    ("silt", "Silt"),
                ],
                max_length=50,
            ),
        ),
    ]
