# Generated by Django 5.1.2 on 2024-12-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cropplan_daily_plan_alter_cropplan_pesticides_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("climate_description", models.TextField()),
                ("soil_description", models.TextField()),
                ("previous_crop_impact", models.TextField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.farm"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendedCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_number",
                    models.CharField(
                        choices=[
                            ("1", "Option 1: Focus on Pulses"),
                            ("2", "Option 2: Diversified Approach"),
                        ],
                        max_length=1,
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("local_name", models.CharField(max_length=100)),
                ("crop_rotation", models.TextField()),
                ("local_adaptation", models.TextField(blank=True, null=True)),
                ("market_demand", models.TextField()),
                ("water_usage", models.TextField(blank=True, null=True)),
                ("growing_season", models.TextField()),
                ("climate", models.TextField(blank=True, null=True)),
                ("maturity", models.TextField(blank=True, null=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="core.croprecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["option_number", "id"],
            },
        ),
    ]
